name: recipe_finder
description: Recipe Finder.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.0
  platform: ^3.1.2
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  json_annotation: ^4.8.1
  http: ^1.1.0
  chopper: ^7.0.6
  logging: ^1.2.0
  provider: ^6.0.5
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  synchronized: ^3.1.0
  sqlbrite: ^2.6.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  chopper_generator: ^7.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/